// flow-typed signature: b7863be2e9a8446c859cec399fce71f2
// flow-typed version: <<STUB>>/react-native-swift_v^1.2.2/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-swift'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-swift' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-swift/bin/cli' {
  declare module.exports: any;
}

declare module 'react-native-swift/bin/postlink' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-swift/bin/cli.js' {
  declare module.exports: $Exports<'react-native-swift/bin/cli'>;
}
declare module 'react-native-swift/bin/postlink.js' {
  declare module.exports: $Exports<'react-native-swift/bin/postlink'>;
}
