// flow-typed signature: 70a3fde503009859f40fda94a047dbd4
// flow-typed version: <<STUB>>/react-native-layout-grid_v^0.0.2/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-layout-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-layout-grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-layout-grid/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-layout-grid/index' {
  declare module.exports: $Exports<'react-native-layout-grid'>;
}
declare module 'react-native-layout-grid/index.js' {
  declare module.exports: $Exports<'react-native-layout-grid'>;
}
declare module 'react-native-layout-grid/styles.js' {
  declare module.exports: $Exports<'react-native-layout-grid/styles'>;
}
