// flow-typed signature: 8e6a306a88c3e3cb148513db39c38ba7
// flow-typed version: <<STUB>>/react-native-get-music-files_v^2.1.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-get-music-files'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-get-music-files' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-get-music-files/index' {
  declare module.exports: $Exports<'react-native-get-music-files'>;
}
declare module 'react-native-get-music-files/index.js' {
  declare module.exports: $Exports<'react-native-get-music-files'>;
}
