// flow-typed signature: 32a2765634b3fcda4cd744d302dd613c
// flow-typed version: <<STUB>>/react-native-track-player_vreact-native-kit/react-native-track-player#dev/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-track-player'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-track-player' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-track-player/example/App' {
  declare module.exports: any;
}

declare module 'react-native-track-player/example/index' {
  declare module.exports: any;
}

declare module 'react-native-track-player/example/react/components/Player' {
  declare module.exports: any;
}

declare module 'react-native-track-player/example/react/components/Screen' {
  declare module.exports: any;
}

declare module 'react-native-track-player/example/react/screens/LandingScreen' {
  declare module.exports: any;
}

declare module 'react-native-track-player/example/react/screens/PlaylistScreen' {
  declare module.exports: any;
}

declare module 'react-native-track-player/example/react/stores/Player' {
  declare module.exports: any;
}

declare module 'react-native-track-player/example/react/stores/Track' {
  declare module.exports: any;
}

declare module 'react-native-track-player/example/service' {
  declare module.exports: any;
}

declare module 'react-native-track-player/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-track-player/lib/ProgressComponent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-track-player/example/App.js' {
  declare module.exports: $Exports<'react-native-track-player/example/App'>;
}
declare module 'react-native-track-player/example/index.js' {
  declare module.exports: $Exports<'react-native-track-player/example/index'>;
}
declare module 'react-native-track-player/example/react/components/Player.js' {
  declare module.exports: $Exports<'react-native-track-player/example/react/components/Player'>;
}
declare module 'react-native-track-player/example/react/components/Screen.js' {
  declare module.exports: $Exports<'react-native-track-player/example/react/components/Screen'>;
}
declare module 'react-native-track-player/example/react/screens/LandingScreen.js' {
  declare module.exports: $Exports<'react-native-track-player/example/react/screens/LandingScreen'>;
}
declare module 'react-native-track-player/example/react/screens/PlaylistScreen.js' {
  declare module.exports: $Exports<'react-native-track-player/example/react/screens/PlaylistScreen'>;
}
declare module 'react-native-track-player/example/react/stores/Player.js' {
  declare module.exports: $Exports<'react-native-track-player/example/react/stores/Player'>;
}
declare module 'react-native-track-player/example/react/stores/Track.js' {
  declare module.exports: $Exports<'react-native-track-player/example/react/stores/Track'>;
}
declare module 'react-native-track-player/example/service.js' {
  declare module.exports: $Exports<'react-native-track-player/example/service'>;
}
declare module 'react-native-track-player/index' {
  declare module.exports: $Exports<'react-native-track-player'>;
}
declare module 'react-native-track-player/index.js' {
  declare module.exports: $Exports<'react-native-track-player'>;
}
declare module 'react-native-track-player/lib/index.js' {
  declare module.exports: $Exports<'react-native-track-player/lib/index'>;
}
declare module 'react-native-track-player/lib/ProgressComponent.js' {
  declare module.exports: $Exports<'react-native-track-player/lib/ProgressComponent'>;
}
